import type { ComponentProps } from "react";
import { source } from "@/lib/source";
import { openapi } from "@/lib/openapi";
import { OpenAPIPage } from "@/components/openapi-page";
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
} from "fumadocs-ui/layouts/docs/page";
import { notFound } from "next/navigation";
import { getMDXComponents } from "@/components/mdx";
import type { Metadata } from "next";
import { createRelativeLink } from "fumadocs-ui/mdx";

export default async function Page(props: PageProps<"/docs/[[...slug]]">) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const MDX = page.data.body;

  return (
    <DocsPage toc={page.data.toc} full={page.data.full}>
      <DocsTitle>{page.data.title}</DocsTitle>
      <DocsDescription>{page.data.description}</DocsDescription>
      <DocsBody>
        <MDX
          components={getMDXComponents({
            a: createRelativeLink(source, page),
            // Reference pages (generated by scripts/generate-reference.mjs)
            // only bake `document`/`operations` into the MDX — the actual
            // bundled schema has to be preloaded per-page here and merged
            // in, or OpenAPIPage crashes reading `payload.bundled`.
            OpenAPIPage: async (mdxProps: Record<string, unknown>) => {
              const preloaded = await openapi.preloadOpenAPIPage(page);
              const mergedProps = {
                ...preloaded,
                ...mdxProps,
              } as ComponentProps<typeof OpenAPIPage>;
              return <OpenAPIPage {...mergedProps} />;
            },
          })}
        />
      </DocsBody>
    </DocsPage>
  );
}

export async function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata(
  props: PageProps<"/docs/[[...slug]]">,
): Promise<Metadata> {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  return {
    title: page.data.title,
    description: page.data.description,
  };
}
